name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose --all-features
  test-with-session:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      env:
        WEBTOON_SESSION: ${{ secrets.WEBTOON_SESSION }}
      run: cargo test --verbose --all-features
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run format check
      run: cargo fmt --check --all-features
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy check
      run: cargo clippy --all-features -- -D warnings
