name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: rui314/setup-mold@v1
    - name: Run tests
      env:
        RUST_BACKTRACE: 1
      run: cargo test --verbose --all-features --release --no-fail-fast
  test-with-session:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: rui314/setup-mold@v1
    - name: Run tests
      env:
        WEBTOON_SESSION: ${{ secrets.WEBTOON_SESSION }}
        RUST_BACKTRACE: 1
      run: cargo test --verbose --all-features --release --no-fail-fast
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: rui314/setup-mold@v1
    - name: Run format check
      run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: rui314/setup-mold@v1
    - name: Run clippy check
      run: cargo clippy --all-features -- -D warnings
