name: Smoke Test

on:
  schedule:
    # Every 3 hours
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable

      - name: Run english webtoons smoke test
        run:  cargo test --all-features --profile test --test english_webtoons_smoke -- --include-ignored --no-capture --test-threads 1

      - name: Run german webtoons smoke test
        run:  cargo test --all-features --profile test --test german_webtoons_smoke -- --include-ignored --no-capture --test-threads 1

      - name: Run spanish webtoons smoke test
        run:  cargo test --all-features --profile test --test spanish_webtoons_smoke -- --include-ignored --no-capture --test-threads 1
