name: Smoke Test

on:
  schedule:
    # Every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - name: Run english webtoons smoke test
        run:  cargo test --all-features --profile test --test english_webtoons_smoke -- --include-ignored --no-capture --test-threads 1
